//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSQLDemoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsOrdered
    {
        public int id { get; set; }
        public string email { get; set; }
        public int productCode { get; set; }
        public string nameofProduct { get; set; }
    }
}
