//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBased
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int id_user { get; set; }
        public string login_user { get; set; }
        public string password_user { get; set; }
    }
}
