//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBased
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string paternalName { get; set; }
        public int phoneNumber { get; set; }
        public string email { get; set; }
    }
}
